# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tailtunnel < Formula
  desc "A web dashboard for Tailscale with browser-based SSH and network diagnostics"
  homepage "https://github.com/rajsinghtech/tailtunnel"
  version "0.0.9"
  license "MIT"

  depends_on "node"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rajsinghtech/tailtunnel/releases/download/v0.0.9/tailtunnel-v0.0.9-darwin-amd64.tar.gz"
      sha256 "8d2c18e17a12698cb97e741da216df2dc2dd6d5f097fb645ca9e4c40ba0069f6"

      def install
        bin.install "tailtunnel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rajsinghtech/tailtunnel/releases/download/v0.0.9/tailtunnel-v0.0.9-darwin-arm64.tar.gz"
      sha256 "d243a0fb7750abdbdd74d0d1544d4edf13099f87a41634a080a32f41cf2cf805"

      def install
        bin.install "tailtunnel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rajsinghtech/tailtunnel/releases/download/v0.0.9/tailtunnel-v0.0.9-linux-amd64.tar.gz"
      sha256 "9d88819fd2354f46d3f388273236131c7f00f48e12c6fca5fcb96a8d4db28438"
      def install
        bin.install "tailtunnel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rajsinghtech/tailtunnel/releases/download/v0.0.9/tailtunnel-v0.0.9-linux-arm64.tar.gz"
      sha256 "94b1c3e4f98e03600f9e9c21c36b177e4a5ecf66afe5c6b519badcc6e0026861"
      def install
        bin.install "tailtunnel"
      end
    end
  end
end
