# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tailtunnel < Formula
  desc "A web dashboard for Tailscale with browser-based SSH and network diagnostics"
  homepage "https://github.com/rajsinghtech/tailtunnel"
  version "0.1.0"
  license "MIT"

  depends_on "node"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rajsinghtech/tailtunnel/releases/download/v0.1.0/tailtunnel-v0.1.0-darwin-amd64.tar.gz"
      sha256 "196c8bb89dcedb02e0dc766a9840d81c9604e417d1355a118b6a7bfba7de412f"

      def install
        bin.install "tailtunnel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rajsinghtech/tailtunnel/releases/download/v0.1.0/tailtunnel-v0.1.0-darwin-arm64.tar.gz"
      sha256 "28809dc64fd3dfa4ad6cbf980eef665f66e3e4e39a7731d39f0b2813f3338f3f"

      def install
        bin.install "tailtunnel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rajsinghtech/tailtunnel/releases/download/v0.1.0/tailtunnel-v0.1.0-linux-amd64.tar.gz"
      sha256 "3cf651a86993dfafb3ab164d7e02de10a9c480cfd70ed6b11dd0e7f1ec91af12"
      def install
        bin.install "tailtunnel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rajsinghtech/tailtunnel/releases/download/v0.1.0/tailtunnel-v0.1.0-linux-arm64.tar.gz"
      sha256 "c2c452a4c5ab0a57a29c684b06e63a05121cacf4913e5f2f1effcd0db08323d4"
      def install
        bin.install "tailtunnel"
      end
    end
  end
end
