# This file was generated by GoReleaser. DO NOT EDIT.
cask "tailtunnel" do
  name "tailtunnel"
  desc "A web dashboard for your Tailscale network with browser-based SSH and network diagnostics"
  homepage "https://github.com/rajsinghtech/tailtunnel"
  version "0.0.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tailtunnel"
  depends_on formula: [
      "node",
    ]

  on_macos do
    on_intel do
      url "https://github.com/rajsinghtech/tailtunnel/releases/download/v#{version}/tailtunnel-v#{version}-darwin-amd64.tar.gz"
      sha256 "eb0dd988df754d430a78bb145be6f9c09ece98f6ee970b979546ac7ddccd4253"
    end
    on_arm do
      url "https://github.com/rajsinghtech/tailtunnel/releases/download/v#{version}/tailtunnel-v#{version}-darwin-arm64.tar.gz"
      sha256 "51031b395bbcec7d8a9b4e75beea9c813c2916790a2f3145c727b3154b457070"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rajsinghtech/tailtunnel/releases/download/v#{version}/tailtunnel-v#{version}-linux-amd64.tar.gz"
      sha256 "3666a44259cefb484ac63f76399357625cb05436db0aff7eec998d1dbb7ea020"
    end
    on_arm do
      url "https://github.com/rajsinghtech/tailtunnel/releases/download/v#{version}/tailtunnel-v#{version}-linux-arm64.tar.gz"
      sha256 "c4c14fc9252bfa5cae7ebacc2ccf9b1c66aaf4f212a44c2088c91b91951fdcec"
    end
  end

  # No zap stanza required
end
