# This file was generated by GoReleaser. DO NOT EDIT.
cask "tailtunnel" do
  name "tailtunnel"
  desc "A web dashboard for your Tailscale network with browser-based SSH and network diagnostics"
  homepage "https://github.com/rajsinghtech/tailtunnel"
  version "0.0.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tailtunnel"
  depends_on formula: [
      "node",
    ]

  on_macos do
    on_intel do
      url "https://github.com/rajsinghtech/tailtunnel/releases/download/v#{version}/tailtunnel-v#{version}-darwin-amd64.tar.gz"
      sha256 "f060cc5f83f610c17b8c99ac248c35ac06b104f49d7e6c74633d2b7f38f707ff"
    end
    on_arm do
      url "https://github.com/rajsinghtech/tailtunnel/releases/download/v#{version}/tailtunnel-v#{version}-darwin-arm64.tar.gz"
      sha256 "0570fb23ff15b2bea8be876402da1cc950c7c495934f4bf1ffbf81a45db6acbd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rajsinghtech/tailtunnel/releases/download/v#{version}/tailtunnel-v#{version}-linux-amd64.tar.gz"
      sha256 "31498991dad5784bab0ebfc6669ba3889a68322c3df67c8926cc8ef19f8aabd7"
    end
    on_arm do
      url "https://github.com/rajsinghtech/tailtunnel/releases/download/v#{version}/tailtunnel-v#{version}-linux-arm64.tar.gz"
      sha256 "4f641648034abe654b18e5924387c47f6eb63cfbb6903589842fd5b8aac05669"
    end
  end

  # No zap stanza required
end
