# This file was generated by GoReleaser. DO NOT EDIT.
cask "tsopencode" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "587f8c09d287a38a256aa4d18b0d4fd2fd0dc6f7b411a7b56e37c1d90ed73120"
      url "https://github.com/rajsinghtech/tsopencode/releases/download/v#{version}/tsopencode-v#{version}-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "dc21db2a91c116d813a212d079e58d63b99db4cb80e96768768f41d75ac9a526"
      url "https://github.com/rajsinghtech/tsopencode/releases/download/v#{version}/tsopencode-v#{version}-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5c38968422f19cd7a7e04cda636aca17196e498f44acd7d643c6b135727b2847"
      url "https://github.com/rajsinghtech/tsopencode/releases/download/v#{version}/tsopencode-v#{version}-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "1dd6b72cf339cde5efdd549350687765f4134d119bfd9c243d6e86616bea9dae"
      url "https://github.com/rajsinghtech/tsopencode/releases/download/v#{version}/tsopencode-v#{version}-linux-arm64.tar.gz"
    end
  end

  name "tsopencode"
  desc "opencode on your Tailscale tailnet via tsnet — no system tailscaled required"
  homepage "https://github.com/rajsinghtech/tsopencode"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tsopencode"

  service "run [opt_bin/'tsopencode']
keep_alive true
log_path var/'log/tsopencode.log'
error_log_path var/'log/tsopencode.log'
environment_variables PATH: std_service_path_env
"

  # No zap stanza required

  caveats <<~EOS
    First-time setup — authenticate your Tailscale node by running once:
      TS_AUTHKEY=tskey-auth-... tsopencode
    State persists to ~/.config/tsopencode/ — subsequent runs are headless.

    To run as a background service (starts at login):
      brew services start tsopencode
  EOS
end
