# This file was generated by GoReleaser. DO NOT EDIT.
cask "tsopencode" do
  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "c0f55300f59a57d6f3058ca597d6ba2628fefa8a6978447f48096c30c58ccd2d"
      url "https://github.com/rajsinghtech/tsopencode/releases/download/v#{version}/tsopencode-v#{version}-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "ee8bba59e16830ec2fcc2a93b9703a22f41ce25da66eef6c8bf53e4b5a5c9e8c"
      url "https://github.com/rajsinghtech/tsopencode/releases/download/v#{version}/tsopencode-v#{version}-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c090c1657f0797ea4b305da095c4da0fea6386e18040a95bc782a75753adebc1"
      url "https://github.com/rajsinghtech/tsopencode/releases/download/v#{version}/tsopencode-v#{version}-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "7a713018bf74d216388838da8886073d1e5929c01092e2d702f7a67ac04d3b22"
      url "https://github.com/rajsinghtech/tsopencode/releases/download/v#{version}/tsopencode-v#{version}-linux-arm64.tar.gz"
    end
  end

  name "tsopencode"
  desc "opencode on your Tailscale tailnet via tsnet — no system tailscaled required"
  homepage "https://github.com/rajsinghtech/tsopencode"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tsopencode"

  service do
    run opt_bin/"tsopencode"
    keep_alive true
    log_path "#{var}/log/tsopencode.log"
    error_log_path "#{var}/log/tsopencode.log"
  end

  # No zap stanza required

  caveats <<~EOS
    First-time setup — authenticate your Tailscale node by running once:
      TS_AUTHKEY=tskey-auth-... tsopencode
    State persists to ~/.config/tsopencode/ — subsequent runs are headless.

    To run as a background service (starts at login):
      brew services start tsopencode
  EOS
end
