# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tailtunnel < Formula
  desc "A web dashboard for Tailscale with browser-based SSH and network diagnostics"
  homepage "https://github.com/rajsinghtech/tailtunnel"
  version "0.1.5"
  license "MIT"

  depends_on "node"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rajsinghtech/tailtunnel/releases/download/v0.1.5/tailtunnel-v0.1.5-darwin-amd64.tar.gz"
      sha256 "522553fd2d64477b23c9c147dfc4c39be50e09d0edec52a5ee5e70f75752ead7"

      def install
        bin.install "tailtunnel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rajsinghtech/tailtunnel/releases/download/v0.1.5/tailtunnel-v0.1.5-darwin-arm64.tar.gz"
      sha256 "0a10b8a90f13d102dc3bf3e4c86bde52074e999d7bbd317dd04e579c83a781c1"

      def install
        bin.install "tailtunnel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rajsinghtech/tailtunnel/releases/download/v0.1.5/tailtunnel-v0.1.5-linux-amd64.tar.gz"
      sha256 "8027c40bf3ff986171957d457468969c0e55fe895d8b2129040aba8e139b8f63"
      def install
        bin.install "tailtunnel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rajsinghtech/tailtunnel/releases/download/v0.1.5/tailtunnel-v0.1.5-linux-arm64.tar.gz"
      sha256 "aa71ab2472604b3b2ff01e030d311b6060adcfb41d75d36af7ab3cc56d886d91"
      def install
        bin.install "tailtunnel"
      end
    end
  end
end
