# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tailbridge < Formula
  desc "Cross-tailnet TCP bridge using Tailscale VIP services"
  homepage "https://github.com/rajsinghtech/tailbridge"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rajsinghtech/tailbridge/releases/download/v0.1.0/tailbridge-v0.1.0-darwin-amd64.tar.gz"
      sha256 "f19800194913d370ec1c7f545ec5add2130625768d3efbf25416d71dd11d4423"

      define_method(:install) do
        bin.install "tailbridge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rajsinghtech/tailbridge/releases/download/v0.1.0/tailbridge-v0.1.0-darwin-arm64.tar.gz"
      sha256 "befae41d2b07a416cce7af0ab71757816292bf2367a09332b38f070a9535f1ec"

      define_method(:install) do
        bin.install "tailbridge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rajsinghtech/tailbridge/releases/download/v0.1.0/tailbridge-v0.1.0-linux-amd64.tar.gz"
      sha256 "dc6dd312a6cfd81bfa34044c79bf596c8fb09e930e5f2dff37cee26295584e18"
      define_method(:install) do
        bin.install "tailbridge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rajsinghtech/tailbridge/releases/download/v0.1.0/tailbridge-v0.1.0-linux-arm64.tar.gz"
      sha256 "1d815d5f0e87fb0150773e12aeeac71fe6e86a2f0db16cefe62c5112bd592c4a"
      define_method(:install) do
        bin.install "tailbridge"
      end
    end
  end
end
