# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tsflow < Formula
  desc "Tailscale network flow visualizer - monitor traffic between nodes in your tailnet"
  homepage "https://github.com/rajsinghtech/tsflow"
  version "1.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rajsinghtech/tsflow/releases/download/v1.3.2/tsflow-v1.3.2-darwin-amd64.tar.gz"
      sha256 "e5410cc7fd0bfe48eaa82bd4d1ddf76db90f920eda6c2b9ad43f9d259c387ae4"

      define_method(:install) do
        bin.install "tsflow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rajsinghtech/tsflow/releases/download/v1.3.2/tsflow-v1.3.2-darwin-arm64.tar.gz"
      sha256 "d8a182f26aa2406484894b7490d22a239527c60f5d685d45779fee0b0905fbbc"

      define_method(:install) do
        bin.install "tsflow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rajsinghtech/tsflow/releases/download/v1.3.2/tsflow-v1.3.2-linux-amd64.tar.gz"
      sha256 "65e8896f6fe1a429866548d191154bdaa9c38cc3405dc6c43fe0e37dde38bdb9"
      define_method(:install) do
        bin.install "tsflow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rajsinghtech/tsflow/releases/download/v1.3.2/tsflow-v1.3.2-linux-arm64.tar.gz"
      sha256 "0cd00979be64ee53b74ead01591ec64985ce49d56eeb325135905b6f95450b3a"
      define_method(:install) do
        bin.install "tsflow"
      end
    end
  end
end
