# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tsflow < Formula
  desc "Tailscale network flow visualizer - monitor traffic between nodes in your tailnet"
  homepage "https://github.com/rajsinghtech/tsflow"
  version "1.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rajsinghtech/tsflow/releases/download/v1.1.7/tsflow-v1.1.7-darwin-amd64.tar.gz"
      sha256 "b77a91c9da574f9e56a659c09a110bd391dbb409107c6234f38bbdff68f3e07b"

      def install
        bin.install "tsflow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rajsinghtech/tsflow/releases/download/v1.1.7/tsflow-v1.1.7-darwin-arm64.tar.gz"
      sha256 "1a40271403fa7e8b1dacc0e4a9fac5ecece7dcb33f2da25bcbb64a3976529711"

      def install
        bin.install "tsflow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rajsinghtech/tsflow/releases/download/v1.1.7/tsflow-v1.1.7-linux-amd64.tar.gz"
      sha256 "259d22dadc1b9b3f20dc5d568b2aa8bf1ef6398d1c9b084789dbdb1e55a484f3"
      def install
        bin.install "tsflow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rajsinghtech/tsflow/releases/download/v1.1.7/tsflow-v1.1.7-linux-arm64.tar.gz"
      sha256 "31f33c84492dde21d2d801c354a413411da968e313e43484ea8b050487db7376"
      def install
        bin.install "tsflow"
      end
    end
  end
end
