# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tsk9s < Formula
  desc "k9s in the browser over Tailscale"
  homepage "https://github.com/rajsinghtech/tsk9s"
  version "0.1.0"
  license "MIT"

  depends_on "k9s"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rajsinghtech/tsk9s/releases/download/v0.1.0/tsk9s-v0.1.0-darwin-amd64.tar.gz"
      sha256 "89592d1fdc8e77cf9dd6d24dc68b0bde55124aa7c29533e9416ea4645b512643"

      define_method(:install) do
        bin.install "tsk9s"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rajsinghtech/tsk9s/releases/download/v0.1.0/tsk9s-v0.1.0-darwin-arm64.tar.gz"
      sha256 "571211c1c7dbf634366099a203e9eed85d8f0cf71e70fbfbde2f417f37b5caaf"

      define_method(:install) do
        bin.install "tsk9s"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rajsinghtech/tsk9s/releases/download/v0.1.0/tsk9s-v0.1.0-linux-amd64.tar.gz"
      sha256 "087f3340d3c7c7ffcbccd2e0a5cd08a1659ee45bb4911c592ece83e6ecf4cf64"
      define_method(:install) do
        bin.install "tsk9s"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rajsinghtech/tsk9s/releases/download/v0.1.0/tsk9s-v0.1.0-linux-arm64.tar.gz"
      sha256 "d59d728d0ee55bc912322065912b23b063eb20e5b1339e4a18a14600bc36ff18"
      define_method(:install) do
        bin.install "tsk9s"
      end
    end
  end
end
