# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tsopencode < Formula
  desc "opencode on your Tailscale tailnet via tsnet — no system tailscaled required"
  homepage "https://github.com/rajsinghtech/tsopencode"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rajsinghtech/tsopencode/releases/download/v0.1.0/tsopencode-v0.1.0-darwin-amd64.tar.gz"
      sha256 "a2ec50da7eb6e9af9ef438a0f20d214e3ff07b1488da8d1ccde0fe5a29df8735"

      define_method(:install) do
        bin.install "tsopencode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rajsinghtech/tsopencode/releases/download/v0.1.0/tsopencode-v0.1.0-darwin-arm64.tar.gz"
      sha256 "9fb95cdfb65347713de7cd1a3dccaee3f2e27853e7acb9ff9b9a8628203c8a5e"

      define_method(:install) do
        bin.install "tsopencode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rajsinghtech/tsopencode/releases/download/v0.1.0/tsopencode-v0.1.0-linux-amd64.tar.gz"
      sha256 "acdebee3e1f6949b44152441726442b8e1b2bcd7ba0093cadfa178cee9b5864e"
      define_method(:install) do
        bin.install "tsopencode"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rajsinghtech/tsopencode/releases/download/v0.1.0/tsopencode-v0.1.0-linux-arm64.tar.gz"
      sha256 "ff3db69b9d9a0016d31f2201819e9486ac9bac6b699d6dc11134a20d1bc3e6fd"
      define_method(:install) do
        bin.install "tsopencode"
      end
    end
  end
end
