# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tsopencode < Formula
  desc "opencode on your Tailscale tailnet via tsnet — no system tailscaled required"
  homepage "https://github.com/rajsinghtech/tsopencode"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rajsinghtech/tsopencode/releases/download/v0.1.7/tsopencode-v0.1.7-darwin-amd64.tar.gz"
      sha256 "5f51f59ec62619abcc43856c519150a2d7523dcddbfdcc82dbfc0b8472b87766"

      define_method(:install) do
        bin.install "tsopencode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rajsinghtech/tsopencode/releases/download/v0.1.7/tsopencode-v0.1.7-darwin-arm64.tar.gz"
      sha256 "66d1a6e025112888a7ff8a306fa042fad35911066d980a34d8a2fc3cd65bb498"

      define_method(:install) do
        bin.install "tsopencode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rajsinghtech/tsopencode/releases/download/v0.1.7/tsopencode-v0.1.7-linux-amd64.tar.gz"
      sha256 "7d9c2861c9a28f82253ebfb9f15371d454a386a152625d52f388ce19e83fced6"
      define_method(:install) do
        bin.install "tsopencode"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rajsinghtech/tsopencode/releases/download/v0.1.7/tsopencode-v0.1.7-linux-arm64.tar.gz"
      sha256 "041b5d758d4cc71373a6cc472316d6d976f357c5c9e9d43113ea39d73858dc63"
      define_method(:install) do
        bin.install "tsopencode"
      end
    end
  end

  def caveats
    <<~EOS
      First-time setup — authenticate your Tailscale node by running once:
        TS_AUTHKEY=tskey-auth-... tsopencode
      State persists to ~/.config/tsopencode/ — subsequent runs are headless.

      To run as a background service (starts at login):
        brew services start tsopencode
    EOS
  end

  service do
    run opt_bin/"tsopencode"
    keep_alive true
    log_path var/"log/tsopencode.log"
    error_log_path var/"log/tsopencode.log"
    environment_variables PATH: std_service_path_env
  end
end
